version = 1

[merge]
require_automerge_label = false
blocking_labels = [
  'blocked',
  'in review',
  'semver:major'
]
method = 'squash'

[merge.message]
title = 'pull_request_title'
strip_html_comments = true
include_coauthors = true

[merge.automerge_dependencies]
# only auto merge "minor" and "patch" version upgrades.
# do not automerge "major" version upgrades.
versions = ["minor", "patch"]
usernames = ["dependabot", "renovate"]
